SELECT  
    {{ dbt_utils.generate_surrogate_key(['order_item_id']) }} AS sales_key,
    order_item_id,
    order_id,
    customer_id,
    store_id,
    product_id,
    channel,
    status,
    order_timestamp,
    order_date,
    currency,
    category,
    subcategory,
    brand,
    line_number,
    quantity,
    unit_price,
    gross_amount,
    discount_amount,
    net_amount,
    tax_amount,
    estimated_cost_amount,
    estimated_margin_amount
FROM {{ REF('int_order_revenue') }}
