SELECT 
    {{ dbt_utils.generate_surrogate_key(['inventory_snapshot_id']) }} AS inventory_snapshot_key,
    inventory_snapshot_id,
    snapshot_date,
    store_name,
    store_id,
    store_city,
    store_region,
    store_format,
    product_id,
    product_name,
    category,
    subcategory,
    stock_on_hand,
    reorder_point,
    reorder_quantity,
    is_stockout,
    is_below_reorder_point,
    stock_retail_value,
    stock_cost_value
FROM {{ ref('int_inventory_position') }}